services:

  elasticsearch:
    image: elasticsearch:8.18.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      discovery.type=single-node: "single-node"
      xpack.security.enabled: "false"
      xpack.security.transport.ssl.enabled: "false"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.18.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./dumps:/data/dumps
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432

volumes:
  esdata:
    driver: local
