id: authors
icon: mdi-account-outline
name: authors
nameSingular: author
displayName: authors
displayNameSingular: author
descr: Creators of scholarly works
eg: Albert Einstein
placeholder: Search scholarly authors
filterName: author
filterKey: authorships.author.id
descrFull: These are the creators of scholarly works. They can be affiliated with
  institutions, have ORCIDs, and have published works. Each author has a unique OpenAlex
  ID.
hintVerb: at
color: green
hasAutocomplete: true
isNative: true
hasSerp: true
highlightFilters:
  - key: has_orcid
    value: true
    displayName: with ORCIDs
  - key: last_known_institutions.is_global_south
    value: true
    displayName: from the Global South
idRegex: (?i)(?:authors\/)?(?:https:\/\/openalex\.org\/)?(a\d+)
showOnEntityPage:
  - id
  - display_name
  - display_name_alternatives
  - last_known_institutions.id
  - affiliations.institution.id
  - ids.orcid
showOnTablePage:
  - display_name
  - count(works)
groupByDefaults:
  - last_known_institutions.id
  - last_known_institutions.country_code
  - has_orcid
columns:
  id:
    id: id
    subjectEntity: authors
    operators:
      - is
      - is not
    defaultOperator: is
    entityId: authors
    objectEntity: authors
    displayName: OpenAlex ID
    type: string
    redshiftDisplayColumn: author_id
    redshiftFilterColumn: author_id
    actions: []
    actionsPopular: []
    isId: true
    icon: mdi-account-outline
    descr: A unique identifier for each author that can be used for filtering works
      by author.
  ids.orcid:
    id: ids.orcid
    subjectEntity: authors
    operators:
      - is
      - is not
    defaultOperator: is
    entityId: authors
    objectEntity:
    displayName: ORCID
    isId: true
    redshiftDisplayColumn: orcid
    redshiftFilterColumn: orcid
    actions:
      - column
      - filter
    type: string
    icon: mdi-account-outline
    descr: A common identifier for researchers that can be used to link their works
      across databases.
  display_name:
    id: display_name
    isColumnMandatory: true
    subjectEntity: authors
    operators:
      - is
      - is not
    defaultOperator: is
    objectEntity:
    displayName: name
    type: string
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    category: other
    redshiftDisplayColumn: display_name
    redshiftFilterColumn: display_name
    icon: mdi-account-outline
    descr: The name of the author.
  display_name.search:
    id: display_name.search
    subjectEntity: authors
    operators:
      - contains
      - does not contain
    defaultOperator: contains
    objectEntity:
    displayName: search display_name
    type: string
    actions:
      - filter
    actionsPopular:
      - filter
    category: search
    redshiftDisplayColumn: display_name
    redshiftFilterColumn: display_name
    icon: mdi-account-outline
    descr: The name of the author.
    isSearchColumn: true
  affiliations.institution.id:
    id: affiliations.institution.id
    isList: true
    subjectEntity: authors
    operators:
      - is
      - is not
    defaultOperator: is
    displayName: Past institutions
    displayNameForColumn: Past institution ID
    entityId: institutions
    objectEntity: institutions
    type: string
    redshiftDisplayColumn: past_affiliation_ids
    redshiftFilterColumn: 
    actions:
      - filter
      - column
    actionsPopular: []
    icon: mdi-town-hall
    descr: The institutions that the author has been affiliated with.
  affiliations.institution.display_name:
    id: affiliations.institution.display_name
    isList: true
    subjectEntity: authors
    operators:
      - is
      - is not
    defaultOperator: is
    displayName: Past institutions
    displayNameForColumn: Past institution name
    entityId: institutions
    objectEntity: institutions
    type: string
    redshiftDisplayColumn: past_affiliation_display_names
    redshiftFilterColumn: 
    actions:
      - column
    actionsPopular: []
    icon: mdi-town-hall
    descr: The institutions that the author has been affiliated with.
  affiliations.institution.type:
    id: affiliations.institution.type
    isList: true
    isId: true
    subjectEntity: authors
    operators:
      - is
      - is not
    defaultOperator: is
    entityId: institution-types
    objectEntity: institution-types
    displayName: Past institutions type
    type: string
    redshiftDisplayColumn: institution_type
    redshiftFilterColumn: institution_type
    actions:
      - filter
    actionsPopular:
      - filter
    icon: mdi-shape-outline
    descr: The type of institutions that the author has been affiliated with which
      are taking from ROR.
  affiliations.institution.country_code:
    id: affiliations.institution.country_code
    isList: true
    subjectEntity: authors
    operators:
      - is
      - is not
    defaultOperator: is
    entityId: countries
    objectEntity: countries
    isId: true
    displayName: country
    type: array
    isCountry: true
    redshiftDisplayColumn: country_code
    redshiftFilterColumn: country_code
    actions:
      - filter
      - group_by
    actionsPopular:
      - filter
    icon: mdi-earth
    descr: The countries of the institutions that the author has been affiliated with.
  last_known_institutions.id:
    id: last_known_institutions.id
    isId: true
    subjectEntity: authors
    operators:
      - is
      - is not
    defaultOperator: is
    displayName: institution
    displayNameForColumn: institution ID
    entityId: institutions
    objectEntity: institutions
    type: string
    redshiftDisplayColumn: affiliation_id
    redshiftFilterColumn: 
    actions:
      - column
      - filter
    actionsPopular:
      - filter
    icon: mdi-town-hall
    descr: The latest institution that the author has been affiliated with in OpenAlex.
  last_known_institutions.display_name:
    id: last_known_institutions.display_name
    subjectEntity: authors
    operators:
      - is
      - is not
    defaultOperator: is
    displayName: institution name
    entityId: institutions
    objectEntity: institutions
    type: string
    redshiftDisplayColumn: affiliation_id
    redshiftFilterColumn: 
    actions:
      - column
    actionsPopular:
    icon: mdi-town-hall
    descr: The names of the latest institution that the author has been affiliated with in OpenAlex.
  last_known_institutions.country_code:
    id: last_known_institutions.country_code
    isList: true
    subjectEntity: authors
    operators:
      - is
      - is not
    defaultOperator: is
    entityId: countries
    objectEntity: countries
    isId: true
    displayName: institution country
    type: array
    isCountry: true
    redshiftDisplayColumn:
    redshiftFilterColumn:
    actions:
      - filter
      - group_by
    actionsPopular:
      - filter
      - group_by
    icon: mdi-earth
    descr: The country of the latest institution that the author has been affiliated
      with in OpenAlex.
  last_known_institutions.type:
    id: last_known_institutions.type
    isList: true
    subjectEntity: authors
    operators:
      - is
      - is not
    defaultOperator: is
    entityId: institution-types
    objectEntity: institution-types
    displayName: Institution type
    isId: true
    type: string
    redshiftDisplayColumn: type
    redshiftFilterColumn: type
    actions:
      - filter
      - group_by
    actionsPopular:
      - filter
    icon: mdi-shape-outline
    descr: The type of the latest institution that the author has been affiliated
      with in OpenAlex.
  has_orcid:
    id: has_orcid
    subjectEntity: authors
    operators:
      - is
    defaultOperator: is
    entityId: authors
    objectEntity:
    displayName: Has an ORCID
    type: boolean
    redshiftDisplayColumn: has_orcid
    redshiftFilterColumn: has_orcid
    actions:
      - filter
      - group_by
    actionsPopular:
      - filter
      - group_by
    icon: mdi-tag-outline
    descr: Whether the author has an ORCID.
  display_name_alternatives:
    id: display_name_alternatives
    isList: true
    subjectEntity: authors
    operators:
      - is
      - is not
    defaultOperator: is
    entityId: authors
    objectEntity:
    displayName: alternate names
    redshiftDisplayColumn:
    redshiftFilterColumn:
    type: array
    actions: []
    actionsPopular: []
    icon: mdi-town-hall
    descr: Alternate names of the author which are determined from the raw author
      name of all works associated with an author.
  related_to_text:
    id: related_to_text
    subjectEntity: authors
    operators:
      - is
    defaultOperator: is
    entityId: authors
    objectEntity:
    displayName: related text
    type: string
    redshiftDisplayColumn: related_to_text
    redshiftFilterColumn: related_to_text
    actions:
      - filter
    actionsPopular:
      - filter
    icon: mdi-text
    descr: Text that the author is related to.
  count(works):
    id: count(works)
    subjectEntity: authors
    operators:
      - is
      - is not
      - is greater than
      - is less than
    defaultOperator: is
    entityId: works
    objectEntity:
    displayName: works count
    type: number
    redshiftDisplayColumn: count(works)
    redshiftFilterColumn: count(works)
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    icon: mdi-book-open-variant
    descr: The number of works that the author has created.
  sum(citations):
    id: sum(citations)
    subjectEntity: authors
    operators:
      - is
      - is not
      - is greater than
      - is less than
    defaultOperator: is
    entityId: works
    objectEntity:
    displayName: citations sum
    type: number
    redshiftDisplayColumn: sum(citations)
    redshiftFilterColumn: sum(citations)
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    icon: mdi-book-open-variant
    descr: Number of times the author has been cited
  mean(fwci):
    id: mean(fwci)
    subjectEntity: authors
    operators:
      - is
      - is not
      - is greater than
      - is less than
    defaultOperator: is
    entityId: works
    objectEntity:
    displayName: mean FWCI
    type: number
    redshiftDisplayColumn: mean_fwci
    redshiftFilterColumn: mean_fwci
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    icon: mdi-book-open-variant
    descr: The mean Field-Weighted Citation Impact (FWCI) of the author's works.
values:
