id: concepts
icon: mdi-tag-outline
name: concepts
nameSingular: concept
displayName: concepts
displayNameSingular: concept
descr: Concepts and fields of study
eg: History
placeholder: Search topics
filterName: concepts
filterKey: concepts.id
descrFull: These are concepts or fields of study that were inherited from MAG (Microsoft
  Academic Graph). Each concept has a unique OpenAlex ID.
hasAutocomplete: true
isNative: true
idRegex: (?i)(?:concepts\/)?(?:https:\/\/openalex\.org\/)?(c\d+)
showOnEntityPage:
  - id
  - display_name
  - description
showOnTablePage:
  - display_name
  - description
columns:
  id:
    id: id
    subjectEntity: concepts
    operators:
      - is
      - is not
    defaultOperator: is
    entityId: concepts
    objectEntity: concepts
    displayName: OpenAlex ID
    isId: true
    type: string
    icon: mdi-tag-outline
    descr: Unique identifier for this concept
  display_name:
    id: display_name
    isColumnMandatory: true
    subjectEntity: concepts
    operators:
      - is
      - is not
    defaultOperator: is
    displayName: name
    type: string
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    category: other
    icon: mdi-account-outline
    descr: The name of this concept or field of study
  display_name.search:
    id: display_name.search
    subjectEntity: concepts
    operators:
      - contains
      - does not contain
    defaultOperator: contains
    displayName: Name search
    type: string
    icon: mdi-magnify
    descr: Display name for search
  count(works):
    id: count(works)
    subjectEntity: concepts
    operators:
      - is
      - is not
      - is greater than
      - is less than
    defaultOperator: is
    entityId: works
    objectEntity:
    displayName: works count
    type: number
    redshiftDisplayColumn: count(works)
    redshiftFilterColumn:
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    icon: mdi-book-open-variant
    descr: The number of works related to the concept
  sum(citations):
    id: sum(citations)
    subjectEntity: concepts
    operators:
      - is
      - is not
      - is greater than
      - is less than
    defaultOperator: is
    entityId: works
    objectEntity:
    displayName: citations sum
    type: number
    redshiftDisplayColumn: sum(citations)
    redshiftFilterColumn:
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    icon: mdi-book-open-variant
    descr: Number of times a work related to the concept has been cited
#  description:
#    id: description
#    subjectEntity: concepts
#    operators:
#      - is
#      - is not
#    defaultOperator: is
#    entityId: concepts
#    objectEntity: concepts
#    displayName: description
#    type: string
#    icon: mdi-tag-outline
#    descr: A description of this concept or field of study
#  level:
#    id: level
#    subjectEntity: concepts
#    operators:
#      - is
#      - is not
#      - is greater than
#      - is less than
#    defaultOperator: is
#    displayName: Level
#    maxPotentialFiltersToShow: 10
#    type: number
#    icon: mdi-tag-outline
#    descr: The level of this concept in the hierarchy of concepts from level 0 to
#      level 6
values:
