id: domains
icon: mdi-tag-outline
name: domains
nameSingular: domain
displayName: domains
displayNameSingular: domain
descr: what works are about
eg: Life sciences
placeholder: Search domains
filterName: domains
filterKey: primary_topic.domain.id
descrFull: These are the domains of scholarly works which are the highest level description
  for a subject area of a work. Each domain has a unique OpenAlex ID.
hasAutocomplete: false
isNative: false
idRegex: (?:https:\/\/openalex\.org\/domains\/|domains\/)(\d+)
showOnEntityPage:
  - id
  - display_name
  - description
  - display_name_alternatives
  - fields
  - siblings
showOnTablePage:
  - display_name
columns:
  id:
    id: id
    subjectEntity: domains
    operators:
      - is
      - is not
    defaultOperator: is
    entityId: domains
    objectEntity:
    displayName: OpenAlex ID
    isId: true
    type: string
    redshiftDisplayColumn: id
    redshiftFilterColumn: id
    icon: mdi-tag-outline
    descr: Unique identifier for the domain
  display_name:
    id: display_name
    isColumnMandatory: true
    subjectEntity: domains
    operators:
      - is
      - is not
    defaultOperator: is
    objectEntity:
    displayName: name
    type: string
    redshiftDisplayColumn: display_name
    redshiftFilterColumn:
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    category: other
    icon: mdi-account-outline
    descr: The name of the domain
  display_name.search:
    id: display_name.search
    subjectEntity: domains
    operators:
      - contains
      - does not contain
    defaultOperator: contains
    objectEntity:
    displayName: search display_name
    type: string
    redshiftDisplayColumn:
    redshiftFilterColumn:
    actions:
      - filter
    actionsPopular:
      - filter
    category: search
    icon: mdi-account-outline
    descr: The name of the domain
    isSearchColumn: true
  count(works):
    id: count(works)
    subjectEntity: domains
    operators:
      - is
      - is not
      - is greater than
      - is less than
    defaultOperator: is
    entityId: works
    objectEntity:
    displayName: works count
    type: number
    redshiftDisplayColumn: count(works)
    redshiftFilterColumn:
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    icon: mdi-book-open-variant
    descr: The number of works that fall under this domain
  sum(citations):
    id: sum(citations)
    subjectEntity: fields
    operators:
      - is
      - is not
      - is greater than
      - is less than
    defaultOperator: is
    entityId: works
    objectEntity:
    displayName: citations sum
    type: number
    redshiftDisplayColumn: sum(citations)
    redshiftFilterColumn:
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    icon: mdi-book-open-variant
    descr: Number of times that works under this domain have been cited
#  description:
#    id: description
#    subjectEntity: domains
#    operators:
#      - is
#      - is not
#    defaultOperator: is
#    entityId: domains
#    objectEntity:
#    displayName: description
#    type: string
#    redshiftDisplayColumn: description
#    redshiftFilterColumn:
#    actions:
#      - column
#    icon: mdi-tag-outline
#    descr: A description of the domain
#  fields:
#    id: fields
#    isList: true
#    subjectEntity: domains
#    operators:
#      - is
#      - is not
#    defaultOperator: is
#    entityId: fields
#    objectEntity:
#    displayName: fields (children)
#    type: array
#    redshiftDisplayColumn:
#    redshiftFilterColumn:
#    actions: []
#    icon: mdi-tag-outline
#    descr: The set of fields that are children of this domain
#  siblings:
#    id: siblings
#    isList: true
#    subjectEntity: domains
#    operators:
#      - is
#      - is not
#    defaultOperator: is
#    entityId: domains
#    objectEntity: domains
#    displayName: other domains (siblings)
#    type: array
#    redshiftDisplayColumn:
#    redshiftFilterColumn:
#    actions: []
#    icon: mdi-tag-outline
#    descr: The set of domains that are siblings of this domain
values:
  - id: domains/3
    display_name: Physical Sciences
  - id: domains/2
    display_name: Social Sciences
  - id: domains/4
    display_name: Health Sciences
  - id: domains/1
    display_name: Life Sciences
