id: funders
icon: mdi-cash-multiple
name: funders
nameSingular: funder
displayName: funders
displayNameSingular: funder
descr: Organization funding works via grants
eg: US National Science Foundation
placeholder: Search research funders
filterName: grants.funder
filterKey: grants.funder
descrFull: These are the organizations that fund research works via grants. Each funder
  has a unique OpenAlex ID.
color: brown
hasAutocomplete: true
isNative: true
idRegex: (?i)(?:funders\/)?(?:https:\/\/openalex\.org\/)?(f\d+)
showOnEntityPage:
  - id
  - display_name
  - description
  - homepage_url
  - doi
  - crossref_id
  - country_code
showOnTablePage:
  - display_name
columns:
  id:
    id: id
    subjectEntity: funders
    operators:
      - is
      - is not
    defaultOperator: is
    entityId: funders
    objectEntity:
    displayName: OpenAlex ID
    isId: true
    type: string
    redshiftDisplayColumn: id
    redshiftFilterColumn: funder_id
    actions: []
    icon: mdi-cash-multiple
    descr: Unique identifier for the funder
  display_name:
    id: display_name
    isColumnMandatory: true
    subjectEntity: funders
    operators:
      - is
      - is not
    defaultOperator: is
    objectEntity:
    displayName: name
    type: string
    redshiftDisplayColumn: display_name
    redshiftFilterColumn: display_name
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    category: other
    icon: mdi-account-outline
    descr: The name of the funder
  display_name.search:
    id: display_name.search
    subjectEntity: funders
    operators:
      - contains
      - does not contain
    defaultOperator: contains
    objectEntity:
    displayName: search display_name
    type: string
    redshiftDisplayColumn:
    redshiftFilterColumn: display_name
    actions:
      - filter
    actionsPopular:
      - filter
    category: search
    icon: mdi-account-outline
    descr: The name of the funder
    isSearchColumn: true
  country_code:
    id: country_code
    subjectEntity: funders
    operators:
      - is
      - is not
    defaultOperator: is
    entityId: countries
    objectEntity: countries
    displayName: Country
    isId: true
    type: object
    isExternalId: true
    externalIdPrefix: countries
    isCountry: true
    redshiftDisplayColumn: country_code_formatted
    redshiftFilterColumn: country_code
    actions:
      - column
      - filter
    actionsPopular:
      - filter
    icon: mdi-earth
    descr: The country in which the funder is based
  doi:
    id: doi
    subjectEntity: funders
    operators:
      - is
      - is not
    defaultOperator: is
    entityId: works
    objectEntity:
    displayName: DOI
    isId: true
    type: string
    redshiftDisplayColumn: doi
    redshiftFilterColumn: doi
    category: ids
    actions:
      - column
      - filter
    icon: mdi-file-document-outline
    descr: The DOI of the funder
  crossref_id:
    id: crossref_id
    subjectEntity: funders
    operators:
      - is
      - is not
    defaultOperator: is
    objectEntity:
    displayName: crossref id
    isId: true
    type: string
    redshiftDisplayColumn: crossref_id
    redshiftFilterColumn: crossref_id
    category: ids
    actions:
      - column
    icon: mdi-file-document-outline
    descr: The crossref id of the funder
  description:
    id: description
    subjectEntity: funders
    operators:
      - is
      - is not
    defaultOperator: is
    objectEntity:
    displayName: description
    isId: true
    type: string
    redshiftDisplayColumn: description
    redshiftFilterColumn: description
    category: ids
    actions:
      - column
    icon: mdi-file-document-outline
    descr: A description of the funder
  homepage_url:
    id: homepage_url
    subjectEntity: funders
    operators:
      - is
      - is not
    defaultOperator: is
    objectEntity:
    displayName: description
    isId: false
    type: string
    redshiftDisplayColumn:
    redshiftFilterColumn:
    category: ids
    actions:
    icon: mdi-file-document-outline
    descr: Homepage url of the funder
  count(works):
    id: count(works)
    subjectEntity: funders
    operators:
      - is
      - is not
      - is greater than
      - is less than
    defaultOperator: is
    entityId: works
    objectEntity:
    displayName: works count
    type: number
    redshiftDisplayColumn: count(works)
    redshiftFilterColumn:
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    icon: mdi-book-open-variant
    descr: The number of works funded by this funder
  sum(citations):
    id: sum(citations)
    subjectEntity: funders
    operators:
      - is
      - is not
      - is greater than
      - is less than
    defaultOperator: is
    entityId: works
    objectEntity:
    displayName: citations sum
    type: number
    redshiftDisplayColumn: sum(citations)
    redshiftFilterColumn:
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    icon: mdi-book-open-variant
    descr: Number of times works funded by this funder have been cited
  mean(fwci):
    id: mean(fwci)
    subjectEntity: funders
    operators:
      - is
      - is not
      - is greater than
      - is less than
    defaultOperator: is
    entityId: works
    objectEntity:
    displayName: mean fwci
    type: number
    redshiftDisplayColumn: mean_fwci
    redshiftFilterColumn: mean_fwci
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    icon: mdi-book-open-variant
    descr: The mean field-weighted citation impact of works funded by this funder
values:
