id: institutions
icon: mdi-town-hall
name: institutions
nameSingular: institution
displayName: institutions
displayNameSingular: institution
descr: Institutions (universities and research centers)
eg: Harvard University
placeholder: Search academic institutions
filterName: institutions
filterKey: authorships.institutions.lineage
descrFull: The institution (university or research center) where an author is affiliated.
  All institutions have a Research Organization Registry (ROR) ID.
hintVerb: in
color: purple
hasAutocomplete: true
isNative: true
hasSerp: true
showOnEntityPage:
  - id
  - display_name
  - homepage_url
  - display_name_alternatives
  - parent_institutions
  - child_institutions
  - related_institutions
  - ids.ror
showOnTablePage:
  - display_name
  - count(works)
idRegex: (?i)(?:institutions\/)?(?:https:\/\/openalex\.org\/)?(i\d+)
groupByDefaults:
  - country_code
  - type
columns:
  id:
    id: id
    subjectEntity: institutions
    operators:
      - is
      - is not
    defaultOperator: is
    entityId: institutions
    objectEntity:
    displayName: OpenAlex ID
    redshiftDisplayColumn: id
    redshiftFilterColumn: affiliation_id
    isId: true
    type: string
    icon: mdi-town-hall
    descr: The unique identifier for the institution in OpenAlex
  display_name:
    id: display_name
    isColumnMandatory: true
    subjectEntity: institutions
    operators:
      - is
      - is not
    defaultOperator: is
    objectEntity:
    displayName: name
    type: string
    redshiftDisplayColumn: display_name
    redshiftFilterColumn: display_name
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    category: other
    icon: mdi-account-outline
    descr: The name of the institution
  display_name.search:
    id: display_name.search
    subjectEntity: institutions
    operators:
      - contains
      - does not contain
    defaultOperator: contains
    objectEntity:
    displayName: search display_name
    type: string
    redshiftDisplayColumn: display_name
    redshiftFilterColumn: display_name
    actions:
      - filter
    actionsPopular:
      - filter
    category: search
    icon: mdi-account-outline
    descr: The name of the institution
    isSearchColumn: true
  ids.ror:
    id: ids.ror
    subjectEntity: institutions
    operators:
      - is
      - is not
    defaultOperator: is
    entityId: institutions
    objectEntity:
    displayName: ROR
    isId: true
    type: string
    redshiftDisplayColumn: ror
    redshiftFilterColumn: ror
    icon: mdi-town-hall
    descr: The unique identifier for the institution in the Research Organization
      Registry (ROR)
  country_code:
    id: country_code
    subjectEntity: institutions
    operators:
      - is
      - is not
    defaultOperator: is
    entityId: countries
    objectEntity: countries
    displayName: Country
    isId: true
    type: object
    isExternalId: true
    externalIdPrefix: countries
    isCountry: true
    redshiftDisplayColumn: country_code_formatted
    redshiftFilterColumn: country_code
    actions:
      - filter
    actionsPopular:
      - filter
    icon: mdi-earth
    descr: The country where the institution is located
  type:
    id: type
    subjectEntity: institutions
    operators:
      - is
      - is not
    defaultOperator: is
    entityId: institution-types
    objectEntity: institution-types
    displayName: Institution type
    redshiftDisplayColumn: type_formatted
    redshiftFilterColumn: type
    isExternalId: true
    externalIdPrefix: institution-types
    isId: true
    type: object
    actions:
      - column
      - filter
    actionsPopular:
      - filter
    icon: mdi-shape-outline
    descr: The type of institution as seen in ROR
  display_name_alternatives:
    id: display_name_alternatives
    isList: true
    subjectEntity: institutions
    operators:
      - is
      - is not
    defaultOperator: is
    objectEntity:
    displayName: alternate names
    redshiftDisplayColumn:
    redshiftFilterColumn:
    type: array
    actions: []
    actionsPopular: []
    icon: mdi-town-hall
    descr: Alternative names or acronyms for the institution
  homepage_url:
    id: homepage_url
    subjectEntity: institutions
    operators:
      - is
      - is not
    defaultOperator: is
    objectEntity:
    displayName: Homepage URL
    isId: false
    type: string
    redshiftDisplayColumn:
    redshiftFilterColumn:
    category: ids
    actions: []
    icon: mdi-file-document-outline
    descr: Homepage url of the institution
  parent_institutions:
    id: parent_institutions
    isList: true
    subjectEntity: institutions
    operators:
      - is
      - is not
    defaultOperator: is
    objectEntity: institutions
    displayName: parent institutions
    redshiftDisplayColumn:
    redshiftFilterColumn:
    type: array
    actions: []
    actionsPopular: []
    icon: mdi-town-hall
    descr: The parent institutions of the institution
  child_institutions:
    id: child_institutions
    isList: true
    subjectEntity: institutions
    operators:
      - is
      - is not
    defaultOperator: is
    objectEntity: institutions
    displayName: child institutions
    redshiftDisplayColumn:
    redshiftFilterColumn:
    type: array
    actions: []
    actionsPopular: []
    icon: mdi-town-hall
    descr: The child institutions of the institution
  related_institutions:
    id: related_institutions
    isList: true
    subjectEntity: institutions
    operators:
      - is
      - is not
    defaultOperator: is
    objectEntity: institutions
    displayName: related institutions
    redshiftDisplayColumn:
    redshiftFilterColumn:
    type: array
    actions: []
    actionsPopular: []
    icon: mdi-town-hall
    descr: Other institutions that are related to the institution
  mean(fwci):
    id: mean(fwci)
    subjectEntity: institutions
    operators:
      - is
      - is not
      - is greater than
      - is less than
    defaultOperator: is
    objectEntity:
    displayName: mean fwci
    type: number
    redshiftDisplayColumn: mean_fwci
    redshiftFilterColumn: mean_fwci
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    icon: mdi-book-open-variant
    descr: The mean Field-Weighted Citation Impact (FWCI) of the institution across
      all works
  count(works):
    id: count
    subjectEntity: institutions
    operators:
      - is
      - is not
      - is greater than
      - is less than
    defaultOperator: is
    objectEntity:
    displayName: works count
    type: number
    redshiftDisplayColumn: count(works)
    redshiftFilterColumn: count(works)
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    icon: mdi-book-open-variant
    descr: The number of works affiliated with the institution in OpenAlex
  sum(citations):
    id: sum(citations)
    subjectEntity: institutions
    operators:
      - is
      - is not
      - is greater than
      - is less than
    defaultOperator: is
    objectEntity:
    displayName: citation sum
    type: number
    redshiftDisplayColumn: sum(citations)
    redshiftFilterColumn: sum(citations)
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    icon: mdi-book-open-variant
    descr: The sum of citations for this institution in OpenAlex
  percent(is_open_access):
    id: percent(is_open_access)
    subjectEntity: institutions
    operators:
      - is
      - is not
      - is greater than
      - is less than
    defaultOperator: is
    objectEntity:
    displayName: is open access %
    type: number
    redshiftDisplayColumn: percent(is_open_access)
    redshiftFilterColumn: percent(is_open_access)
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    icon: mdi-book-open-variant
    descr: The percentage of works affiliated with the institution that are open access
values:
