id: institution-types
icon: mdi-shape-outline
name: institution-types
nameSingular: institution type
displayName: institution types
displayNameSingular: institution type
descr: institution type
eg: company
placeholder: Search institution types
filterName: institution type
filterKey: authorships.institutions.type
descrFull: The type of institution as seen in ROR
hasAutocomplete: false
isNative: false
idRegex: 
  (?:https:\/\/openalex\.org\/institution-types\/|institution-types\/)([a-zA-Z\-]+)
showOnEntityPage:
  - id
  - display_name
showOnTablePage:
  - display_name
columns:
  id:
    id: id
    subjectEntity: institution-types
    operators:
      - is
      - is not
    defaultOperator: is
    entityId: institution-types
    objectEntity:
    displayName: Institution ID
    isId: true
    type: string
    redshiftDisplayColumn: id
    redshiftFilterColumn: id
    actions: []
    icon: mdi-tag-outline
    descr: The unique identifier for the institution type
  display_name:
    id: display_name
    isColumnMandatory: true
    subjectEntity: institution-types
    operators:
      - is
      - is not
    defaultOperator: is
    objectEntity:
    displayName: name
    type: string
    redshiftDisplayColumn: display_name
    redshiftFilterColumn:
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    category: other
    icon: mdi-account-outline
    descr: The name of the institution type
  display_name.search:
    id: display_name.search
    subjectEntity: institution-types
    operators:
      - contains
      - does not contain
    defaultOperator: contains
    objectEntity:
    displayName: search display_name
    type: string
    redshiftDisplayColumn:
    redshiftFilterColumn:
    actions:
      - filter
    actionsPopular:
      - filter
    category: search
    icon: mdi-account-outline
    descr: The name of the institution type
    isSearchColumn: true
  count(works):
    id: count(works)
    subjectEntity: institution-types
    operators:
      - is
      - is not
      - is greater than
      - is less than
    defaultOperator: is
    entityId: works
    objectEntity:
    displayName: works count
    type: number
    redshiftDisplayColumn: count(works)
    redshiftFilterColumn:
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    icon: mdi-book-open-variant
    descr: The number of works created by this institution type
  sum(citations):
    id: sum(citations)
    subjectEntity: institution-types
    operators:
      - is
      - is not
      - is greater than
      - is less than
    defaultOperator: is
    entityId: works
    objectEntity:
    displayName: citations sum
    type: number
    redshiftDisplayColumn: sum(citations)
    redshiftFilterColumn:
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    icon: mdi-book-open-variant
    descr: Number of times works by this institution type have been cited
values:
  - id: institution-types/education
    display_name: education
  - id: institution-types/healthcare
    display_name: healthcare
  - id: institution-types/facility
    display_name: facility
  - id: institution-types/government
    display_name: government
  - id: institution-types/company
    display_name: company
  - id: institution-types/nonprofit
    display_name: nonprofit
  - id: institution-types/other
    display_name: other
  - id: institution-types/archive
    display_name: archive
