id: keywords
icon: mdi-tag-outline
name: keywords
nameSingular: keyword
displayName: keywords
displayNameSingular: keyword
descr: what works are about
eg: Cardiac imaging
placeholder: Search keywords
filterName: keywords
filterKey: keywords.id
descrFull: Keywords are the lowest level of categorization for works. They are used
  to specifically describe a work.
hintVerb: ':'
hasAutocomplete: true
isNative: false
idRegex: (?:https:\/\/openalex\.org\/keywords\/|keywords\/)([a-zA-Z0-9\-]+)
showOnEntityPage:
  - id
  - display_name
showOnTablePage:
  - display_name
  - count(works)
sortByDefault: count(works)
sortDirDefault: desc
columns:
  id:
    id: id
    subjectEntity: keywords
    operators:
      - is
      - is not
    defaultOperator: is
    entityId: keywords
    objectEntity:
    displayName: Keyword ID
    isId: true
    type: string
    redshiftDisplayColumn: keyword_id
    redshiftFilterColumn: keyword_id
    actions: []
    icon: mdi-tag-outline
    descr: The unique identifier for the keyword in OpenAlex
  display_name:
    id: display_name
    isColumnMandatory: true
    subjectEntity: keywords
    operators:
      - contains
      - does not contain
    defaultOperator: contains
    objectEntity:
    displayName: keyword name
    type: string
    redshiftDisplayColumn: display_name
    redshiftFilterColumn: display_name
    actions:
      - filter
      - sort
      - column
    actionsPopular:
      - sort
      - column
    category: other
    icon: mdi-account-outline
    descr: The name of the keyword
  count(works):
    id: count(works)
    subjectEntity: keywords
    operators:
      - is
      - is not
      - is greater than
      - is less than
    defaultOperator: is
    objectEntity:
    displayName: works count
    type: number
    redshiftDisplayColumn: count(works)
    redshiftFilterColumn: count(works)
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    category: other
    icon: mdi-account-outline
    descr: The number of works that have this keyword
  sum(citations):
    id: sum(citations)
    subjectEntity: keywords
    operators:
      - is
      - is not
      - is greater than
      - is less than
    defaultOperator: is
    objectEntity:
    displayName: citation sum
    type: number
    redshiftDisplayColumn: sum(citations)
    redshiftFilterColumn: sum(citations)
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    icon: mdi-book-open-variant
    descr: The sum of citations for this keyword in OpenAlex
  mean(fwci):
    id: mean(fwci)
    subjectEntity: keywords
    operators:
      - is
      - is not
      - is greater than
      - is less than
    defaultOperator: is
    objectEntity:
    displayName: mean FWCI
    type: number
    redshiftDisplayColumn: mean_fwci
    redshiftFilterColumn: mean_fwci
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    icon: mdi-book-open-variant
    descr: The mean Field-Weighted Citation Impact for works with this keyword
values:
