id: publishers
icon: mdi-domain
name: publishers
nameSingular: publisher
displayName: publishers
displayNameSingular: publisher
descr: Company hosting journals
eg: Elsevier
placeholder: Search academic publishers
filterName: primary_location.source.publisher_lineage
filterKey: primary_location.source.publisher_lineage
descrFull: The publisher of scholarly articles, usually a company or organization.
color: pink
hasAutocomplete: true
isNative: true
idRegex: (?i)(?:publishers\/)?(?:https:\/\/openalex\.org\/)?(p\d+)
showOnEntityPage:
  - id
  - display_name
  - homepage_url
  - alternate_titles
showOnTablePage:
  - display_name
  - count(works)
columns:
  id:
    id: id
    subjectEntity: publishers
    operators:
      - is
      - is not
    defaultOperator: is
    entityId: publishers
    objectEntity:
    displayName: OpenAlex ID
    isId: true
    type: string
    redshiftDisplayColumn: id
    redshiftFilterColumn: publisher_id
    actions: []
    icon: mdi-domain
    descr: The unique identifier for the publisher in OpenAlex.
  display_name:
    id: display_name
    isColumnMandatory: true
    subjectEntity: publishers
    operators:
      - is
      - is not
    defaultOperator: is
    objectEntity:
    displayName: name
    type: string
    redshiftDisplayColumn: display_name
    redshiftFilterColumn: display_name
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    category: other
    icon: mdi-account-outline
    descr: The name of the publisher.
  display_name.search:
    id: display_name.search
    subjectEntity: publishers
    operators:
      - contains
      - does not contain
    defaultOperator: contains
    objectEntity:
    displayName: search display_name
    type: string
    redshiftDisplayColumn:
    redshiftFilterColumn: display_name
    actions:
      - filter
    actionsPopular:
      - filter
    category: search
    icon: mdi-account-outline
    descr: The name of the publisher.
    isSearchColumn: true
  country_code:
    id: country_code
    subjectEntity: publishers
    operators:
      - is
      - is not
    defaultOperator: is
    entityId: countries
    objectEntity: countries
    displayName: Country
    isId: true
    type: object
    redshiftDisplayColumn: country_code_formatted
    redshiftFilterColumn: country_code
    isExternalId: true
    externalIdPrefix: countries
    isCountry: true
    actions:
      - filter
    actionsPopular:
      - filter
    icon: mdi-earth
    descr: The country where the publisher is located.
  homepage_url:
    id: homepage_url
    subjectEntity: publishers
    operators:
      - is
      - is not
    defaultOperator: is
    objectEntity:
    displayName: Homepage URL
    isId: false
    type: string
    redshiftDisplayColumn:
    redshiftFilterColumn:
    category: ids
    actions: [ ]
    icon: mdi-file-document-outline
    descr: Homepage url of the publisher
  alternative_titles:
    id: alternative_titles
    subjectEntity: publishers
    objectEntity:
    displayName: Alternative titles
    isId: false
    type: array
    redshiftDisplayColumn:
    redshiftFilterColumn:
    category: ids
    actions: [ ]
    icon: mdi-file-document-outline
    descr: Alternative titles of the publisher
  count(works):
    id: count(works)
    subjectEntity: publishers
    operators:
      - is
      - is not
      - is greater than
      - is less than
    defaultOperator: is
    objectEntity:
    displayName: works count
    type: number
    redshiftDisplayColumn: count(works)
    redshiftFilterColumn: count(works)
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    category: other
    icon: mdi-account-outline
    descr: The number of works that are from this publisher
  sum(citations):
    id: sum(citations)
    subjectEntity: publishers
    operators:
      - is
      - is not
      - is greater than
      - is less than
    defaultOperator: is
    objectEntity:
    displayName: citation sum
    type: number
    redshiftDisplayColumn: sum(citations)
    redshiftFilterColumn: sum(citations)
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    icon: mdi-book-open-variant
    descr: The sum of citations for this publisher in OpenAlex
  mean(fwci):
    id: mean(fwci)
    subjectEntity: publishers
    operators:
      - is
      - is not
      - is greater than
      - is less than
    defaultOperator: is
    objectEntity:
    displayName: mean fwci
    type: number
    redshiftDisplayColumn: mean_fwci
    redshiftFilterColumn: mean_fwci
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    icon: mdi-book-open-variant
    descr: The mean field-weighted citation impact for this publisher in OpenAlex
values:
