id: source-types
icon: mdi-shape-outline
name: source-types
nameSingular: source type
displayName: source types
displayNameSingular: source type
descr: Source type
eg: journal
placeholder: Search source types
filterName: source type
filterKey: primary_location.source.type
descrFull: The type of source, such as a journal, repository, or conference.
hasAutocomplete: false
isNative: false
idRegex: (?:https:\/\/openalex\.org\/source-types\/|source-types\/)([a-zA-Z\-]+)
showOnEntityPage:
  - id
  - display_name
  - description
showOnTablePage:
  - display_name
  - count(works)
sortByDefault: count(works)
sortDirDefault: desc
columns:
  id:
    id: id
    subjectEntity: source-types
    operators:
      - is
      - is not
    defaultOperator: is
    entityId: source-types
    objectEntity:
    displayName: Source Type ID
    isId: true
    type: string
    redshiftDisplayColumn: source_type_id
    redshiftFilterColumn: source_type_id
    actions: []
    icon: mdi-shape-outline
    descr: The unique identifier for the source type in OpenAlex.
  display_name:
    id: display_name
    subjectEntity: source-types
    operators:
      - is
      - is not
    defaultOperator: is
    objectEntity:
    entityId: source-types
    displayName: source type
    type: string
    redshiftDisplayColumn: display_name
    redshiftFilterColumn: display_name
    actions:
      - column
      - sort
    actionsPopular:
      - column
    icon: mdi-shape-outline
    descr: The name of the source type.
  display_name.search:
    id: display_name.search
    subjectEntity: source-types
    operators:
      - contains
      - does not contain
    defaultOperator: contains
    objectEntity:
    entityId: source-types
    displayName: search display_name
    type: string
    redshiftDisplayColumn: display_name
    redshiftFilterColumn: display_name
    actions:
      - filter
    actionsPopular:
      - filter
    icon: mdi-shape-outline
    descr: The name of the source type.
    isSearchColumn: true
    category: search
  count(works):
    id: count(works)
    subjectEntity: source-types
    operators:
      - is
      - is not
      - is greater than
      - is less than
    defaultOperator: is
    objectEntity: works
    displayName: number of works
    type: number
    redshiftDisplayColumn: count(works)
    redshiftFilterColumn: count(works)
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    category: other
    icon: mdi-account-outline
    descr: The number of works associated with the type of source
  sum(citations):
    id: sum(citations)
    subjectEntity: source-types
    operators:
      - is
      - is not
      - is greater than
      - is less than
    defaultOperator: is
    objectEntity:
    displayName: citation sum
    type: number
    redshiftDisplayColumn: sum(citations)
    redshiftFilterColumn: sum(citations)
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    icon: mdi-book-open-variant
    descr: The sum of citations of works for this source type
values:
  - id: source-types/journal
    display_name: journal
  - id: source-types/repository
    display_name: repository
  - id: source-types/ebook platform
    display_name: ebook platform
  - id: source-types/book series
    display_name: book series
  - id: source-types/conference
    display_name: conference
  - id: source-types/other
    display_name: other