id: sources
icon: mdi-book-open-outline
name: sources
nameSingular: source
displayName: sources
displayNameSingular: source
descr: Journals, conferences, and repositories
eg: The New England Journal of Medicine
placeholder: Search academic journals & repositories
filterName: primary_location.source
filterKey: primary_location.source.id
descrFull: The source or location of scholarly articles, such as a journal, conference,
  or repository.
hintVerb: published by
color: orange
hasAutocomplete: true
isNative: true
hasSerp: true
highlightFilters:
  - key: is_oa
    value: true
    displayName: that are Open Access
idRegex: (?i)(?:sources\/)?(?:https:\/\/openalex\.org\/)?(s\d+)
showOnEntityPage:
  - id
  - display_name
  - ids.issn
  - type
  - host_organization
  - alternate_titles
  - is_oa
  - is_in_doaj
  - apc_usd
showOnTablePage:
  - display_name
  - count(works)
groupByDefaults:
  - type
  - is_oa
  - is_in_doaj
columns:
  id:
    id: id
    subjectEntity: sources
    operators:
      - is
      - is not
    defaultOperator: is
    entityId:
    objectEntity: sources
    displayName: OpenAlex ID
    isId: true
    type: string
    redshiftDisplayColumn: id
    redshiftFilterColumn: id
    actions: []
    icon: mdi-book-open-outline
    descr: The unique identifier for the source in OpenAlex.
  ids.issn:
    id: ids.issn
    subjectEntity: sources
    operators:
      - is
      - is not
    defaultOperator: is
    objectEntity:
    entityId: sources
    displayName: ISSNs
    isId: true
    type: string
    redshiftDisplayColumn: issn
    redshiftFilterColumn: issn
    actions:
      - column
      - filter
    icon: mdi-book-open-outline
    descr: The International Standard Serial Number (ISSN) of the source.
  display_name:
    id: display_name
    isColumnMandatory: true
    subjectEntity: sources
    operators:
      - is
      - is not
    defaultOperator: is
    objectEntity:
    displayName: name
    type: string
    redshiftDisplayColumn: display_name
    redshiftFilterColumn: display_name
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    category: other
    icon: mdi-account-outline
    descr: The name of the source.
  display_name.search:
    id: display_name.search
    subjectEntity: sources
    operators:
      - contains
      - does not contain
    defaultOperator: contains
    objectEntity:
    displayName: search display_name
    type: string
    redshiftDisplayColumn:
    redshiftFilterColumn: display_name
    actions:
      - filter
    actionsPopular:
      - filter
    category: search
    icon: mdi-account-outline
    descr: The name of the source.
    isSearchColumn: true
  host_organization:
    id: host_organization
    subjectEntity: sources
    operators:
      - is
      - is not
    defaultOperator: is
    entityId: publishers
    objectEntity: publishers
    displayName: Publisher
    type: object
    redshiftDisplayColumn: publisher_id
    redshiftFilterColumn: publisher_id
    actions:
      - filter
      - column
      - sort
    actionsPopular: []
    icon: mdi-domain
    descr: The organization or publisher that publishes the source.
  host_organization_name:
    id: host_organization_name
    subjectEntity: sources
    operators:
      - is
      - is not
    defaultOperator: is
    entityId: publishers
    objectEntity: publishers
    displayName: Publisher
    type: object
    redshiftDisplayColumn:
    redshiftFilterColumn:
    actions: [ ]
    actionsPopular: [ ]
    icon: mdi-domain
    descr: Name search of the host organization that publishes the source
  type:
    id: type
    subjectEntity: sources
    operators:
      - is
      - is not
    defaultOperator: is
    entityId: source-types
    objectEntity: source-types
    displayName: Source type
    isId: true
    isExternalId: true
    externalIdPrefix: source-types
    type: object
    redshiftDisplayColumn: type_formatted
    redshiftFilterColumn: type
    actions:
      - column
      - filter
    actionsPopular:
      - filter
    icon: mdi-shape-outline
    descr: The type of source.
  apc_usd:
    id: apc_usd
    isCurrency: true
    subjectEntity: sources
    operators:
      - is
      - is not
      - is greater than
      - is less than
    defaultOperator: is
    objectEntity:
    displayName: Article Processing Charge
    type: number
    redshiftDisplayColumn:
    redshiftFilterColumn:
    actions: []
    actionsPopular: []
    icon: mdi-cash
    descr: The Article Processing Charge (APC) in USD for the source.
  is_oa:
    id: is_oa
    subjectEntity: sources
    operators:
      - is
    defaultOperator: is
    objectEntity:
    displayName: fully open access
    type: boolean
    redshiftDisplayColumn:
    redshiftFilterColumn:
    actions: []
    actionsPopular: []
    icon: mdi-lock-open-outline
    descr: Whether the source is fully open access.
  is_in_doaj:
    id: is_in_doaj
    subjectEntity: sources
    operators:
      - is
    defaultOperator: is
    objectEntity:
    displayName: In DOAJ
    type: boolean
    redshiftDisplayColumn: is_in_doaj
    redshiftFilterColumn: is_in_doaj
    actions:
      - column
      - filter
    actionsPopular:
      - filter
    icon: mdi-lock-open-outline
    descr: Whether the source is listed in the Directory of Open Access Journals (DOAJ).
#  alternate_titles:
#    id: alternate_titles
#    isList: true
#    subjectEntity: sources
#    operators:
#      - is
#      - is not
#    defaultOperator: is
#    objectEntity:
#    displayName: alternate names
#    type: array
#    redshiftDisplayColumn:
#    redshiftFilterColumn:
#    actions: []
#    actionsPopular: []
#    icon: mdi-book-open-outline
#    descr: Alternate names for the source.
  count(works):
    id: count(works)
    subjectEntity: sources
    operators:
      - is
      - is not
      - is greater than
      - is less than
    defaultOperator: is
    objectEntity:
    displayName: works count
    type: number
    redshiftDisplayColumn: count(works)
    redshiftFilterColumn: count(works)
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    icon: mdi-book-open-variant
    descr: The number of works published by the source.
  sum(citations):
    id: sum(citations)
    subjectEntity: sources
    operators:
      - is
      - is not
      - is greater than
      - is less than
    defaultOperator: is
    objectEntity:
    displayName: citation sum
    type: number
    redshiftDisplayColumn: sum(citations)
    redshiftFilterColumn: sum(citations)
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    icon: mdi-book-open-variant
    descr: The sum of citations of works for this source
  mean(fwci):
    id: mean(fwci)
    subjectEntity: sources
    operators:
      - is
      - is not
      - is greater than
      - is less than
    defaultOperator: is
    objectEntity:
    displayName: mean FWCI
    type: number
    redshiftDisplayColumn: mean_fwci
    redshiftFilterColumn: mean_fwci
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    icon: mdi-book-open-variant
    descr: The mean Field-Weighted Citation Impact (FWCI) of works for this source
values:
