id: topics
icon: mdi-tag-outline
name: topics
nameSingular: topic
displayName: topics
displayNameSingular: topics
descr: what works are about
eg: RNA sequencing
placeholder: Search topics
filterName: topics
filterKey: primary_topic.id
descrFull: Topics are the fourth level of description of the subject area of works.
  Each topic has a unique OpenAlex ID. Topics are above keywords but below domains,
  fields, and subfields in the hierarchy of research areas in OpenAlex.
hintVerb: ':'
hasAutocomplete: true
isNative: true
idRegex: (?i)(?:topics\/)?(?:https:\/\/openalex\.org\/)?(t\d+)
showOnEntityPage:
  - id
  - display_name
  - description
  - siblings
  - subfield
  - field
  - domain
showOnTablePage:
  - display_name
  - id
  - count(works)
sortByDefault: count(works)
sortDirDefault: desc
columns:
  id:
    id: id
    subjectEntity: topics
    operators:
      - is
      - is not
    defaultOperator: is
    entityId: topics
    objectEntity:
    displayName: Topic ID
    isId: true
    type: string
    actions:
      - filter
      - column
      - sort
    redshiftDisplayColumn: topic_id
    redshiftFilterColumn: topic_id
    icon: mdi-tag-outline
    descr: Unique identifier for the topic in OpenAlex.
  display_name:
    id: display_name
    isColumnMandatory: true
    subjectEntity: topics
    operators:
      - contains
      - does not contain
    defaultOperator: contains
    objectEntity:
    displayName: topic name
    type: string
    redshiftDisplayColumn: display_name
    redshiftFilterColumn: display_name
    actions:
      - filter
      - sort
      - column
    actionsPopular:
      - sort
      - column
    category: other
    icon: mdi-account-outline
    descr: The name of the topic.
  description:
    id: description
    subjectEntity: topics
    operators:
      - is
      - is not
    defaultOperator: is
    entityId: topics
    objectEntity:
    displayName: description
    type: string
    redshiftDisplayColumn: description
    redshiftFilterColumn: description
    actions:
      - column
    icon: mdi-tag-outline
    descr: A description of the topic.
  siblings:
    id: siblings
    isList: true
    subjectEntity: topics
    operators:
      - is
      - is not
    defaultOperator: is
    entityId: topics
    objectEntity: topics
    displayName: related topics (siblings)
    type: array
    redshiftDisplayColumn:
    redshiftFilterColumn:
    actions: []
    icon: mdi-tag-outline
    descr: Other topics that are closely related to this topic.
  subfield:
    id: subfield
    subjectEntity: topics
    operators:
      - is
      - is not
    defaultOperator: is
    entityId: subfields
    objectEntity: subfields
    displayName: subfield (parent)
    type: object
    redshiftDisplayColumn: subfield_id
    redshiftFilterColumn: subfield_id
    actions:
      - filter
      - sort
      - column
    icon: mdi-tag-outline
    descr: The subfield that this topic belongs to.
  field:
    id: field
    subjectEntity: topics
    operators:
      - is
      - is not
    defaultOperator: is
    entityId: fields
    objectEntity: fields
    displayName: field
    type: object
    redshiftDisplayColumn:
    redshiftFilterColumn:
    actions: 
      - filter
      - sort
      - column
    icon: mdi-tag-outline
    descr: The field that this topic belongs to.
  domain:
    id: domain
    subjectEntity: topics
    operators:
      - is
      - is not
    defaultOperator: is
    entityId: domains
    objectEntity: domains
    displayName: domain
    type: string
    redshiftDisplayColumn: domain_id
    redshiftFilterColumn: domain_id
    actions: 
      - filter
      - sort
      - column
    icon: mdi-tag-outline
    descr: The domain that this topic belongs to.
  count(works):
    id: count(works)
    subjectEntity: topics
    operators:
      - is
      - is not
      - is greater than
      - is less than
    defaultOperator: is
    entityId: works
    objectEntity:
    displayName: works count
    type: number
    actions:
      - filter
      - sort
      - column
    redshiftDisplayColumn: count(works)
    redshiftFilterColumn: count(works)
    icon: mdi-tag-outline
    descr: The number of works that are tagged with this topic.
  sum(citations):
    id: sum(citations)
    subjectEntity: topics
    operators:
      - is
      - is not
      - is greater than
      - is less than
    defaultOperator: is
    objectEntity:
    displayName: citation sum
    type: number
    redshiftDisplayColumn: sum(citations)
    redshiftFilterColumn: sum(citations)
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    icon: mdi-book-open-variant
    descr: The sum of works cited that are tagged with this topic
  mean(fwci):
    id: mean(fwci)
    subjectEntity: topics
    operators:
      - is
      - is not
      - is greater than
      - is less than
    defaultOperator: is
    objectEntity:
    displayName: mean FWCI
    type: number
    redshiftDisplayColumn: mean_fwci
    redshiftFilterColumn: mean_fwci
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    icon: mdi-book-open-variant
    descr: The mean Field-Weighted Citation Impact of works that are tagged with this topic
values:
