id: types
icon: mdi-shape-outline
name: types
nameSingular: type
displayName: types
displayNameSingular: type
descr: Work type
eg: article
placeholder: Search work types
filterName: type
filterKey: type
descrFull: The type of work, such as an article, book, or dataset.
hasAutocomplete: false
isNative: false
idRegex: (?:https:\/\/openalex\.org\/types\/|types\/)([a-zA-Z\-]+)
showOnEntityPage:
  - id
  - display_name
  - description
  - crossref_types
showOnTablePage:
  - display_name
columns:
  id:
    id: id
    subjectEntity: types
    operators:
      - is
      - is not
    defaultOperator: is
    entityId: types
    objectEntity:
    displayName: Type ID
    isId: true
    type: string
    redshiftDisplayColumn: id
    redshiftFilterColumn: id
    actions: []
    icon: mdi-tag-outline
    descr: The unique identifier for the work type in OpenAlex.
  display_name:
    id: display_name
    isColumnMandatory: true
    subjectEntity: types
    operators:
      - is
      - is not
    defaultOperator: is
    objectEntity:
    displayName: name
    type: string
    redshiftDisplayColumn: display_name
    redshiftFilterColumn:
    actions:
      - sort
      - column
    actionsPopular:
      - sort
      - column
    category: other
    icon: mdi-account-outline
    descr: The name of the work type.
  display_name.search:
    id: display_name.search
    subjectEntity: types
    operators:
      - contains
      - does not contain
    defaultOperator: contains
    objectEntity:
    displayName: search display_name
    type: string
    redshiftDisplayColumn:
    redshiftFilterColumn:
    actions:
      - filter
    actionsPopular:
      - filter
    category: search
    icon: mdi-account-outline
    descr: The name of the work type.
    isSearchColumn: true
  description:
    id: description
    subjectEntity: types
    operators:
      - is
      - is not
    defaultOperator: is
    entityId: types
    objectEntity:
    displayName: description
    type: string
    redshiftDisplayColumn: description
    redshiftFilterColumn:
    actions:
      - column
    icon: mdi-shape-outline
    descr: A description of the work type.
  crossref_types:
    id: crossref_types
    isList: true
    subjectEntity: types
    operators:
      - is
      - is not
    defaultOperator: is
    entityId: types
    objectEntity:
    displayName: alternate names (Crossref)
    type: array
    redshiftDisplayColumn:
    redshiftFilterColumn:
    actions: []
    icon: mdi-shape-outline
    descr: Alternate names for the work type from Crossref.
values:
  - id: types/article
    display_name: article
  - id: types/book-chapter
    display_name: book-chapter
  - id: types/dataset
    display_name: dataset
  - id: types/preprint
    display_name: preprint
  - id: types/dissertation
    display_name: dissertation
  - id: types/book
    display_name: book
  - id: types/review
    display_name: review
  - id: types/paratext
    display_name: paratext
  - id: types/letter
    display_name: letter
  - id: types/other
    display_name: other
  - id: types/reference-entry
    display_name: reference-entry
  - id: types/report
    display_name: report
  - id: types/editorial
    display_name: editorial
  - id: types/peer-review
    display_name: peer-review
  - id: types/standard
    display_name: standard
  - id: types/erratum
    display_name: erratum
  - id: types/grant
    display_name: grant
  - id: types/supplementary-materials
    display_name: supplementary-materials
